changeLogFile=db/changelog/db.changelog-master.yaml
url=jdbc:postgresql://localhost:5432/conjunto_residencial_control_pagos
username=postgres
password=admin
driver=org.postgresql.Driver
defaultSchemaName=conjunto_residencial_control_pagos