--
-- PostgreSQL database dump
--

--\restrict ME0mcb6t6weQdUYH0vjAboX2M7EYbA18EOGoQgcAPtym7Im9GlOo4ov0OXkxisF

-- Dumped from database version 17.6
-- Dumped by pg_dump version 17.6
--
-- Name: conjunto_residencial_control_pagos; Type: SCHEMA; Schema: -; Owner: postgres
--

CREATE SCHEMA conjunto_residencial_control_pagos;


--ALTER SCHEMA conjunto_residencial_control_pagos OWNER TO postgres;

--
-- Name: pgcrypto; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS pgcrypto WITH SCHEMA conjunto_residencial_control_pagos;


--
-- Name: EXTENSION pgcrypto; Type: COMMENT; Schema: -; Owner: 
--

COMMENT ON EXTENSION pgcrypto IS 'cryptographic functions';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: detalles_facturas; Type: TABLE; Schema: conjunto_residencial_control_pagos; Owner: postgres
--

CREATE TABLE conjunto_residencial_control_pagos.detalles_facturas (
    id integer NOT NULL,
    id_detalle_factura uuid DEFAULT gen_random_uuid() NOT NULL,
    id_factura uuid,
    id_servicio uuid,
    monto bigint NOT NULL
);


--ALTER TABLE conjunto_residencial_control_pagos.detalles_facturas OWNER TO postgres;

--
-- Name: detalles_facturas_id_seq; Type: SEQUENCE; Schema: conjunto_residencial_control_pagos; Owner: postgres
--

ALTER TABLE conjunto_residencial_control_pagos.detalles_facturas ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME conjunto_residencial_control_pagos.detalles_facturas_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: facturas; Type: TABLE; Schema: conjunto_residencial_control_pagos; Owner: postgres
--

CREATE TABLE conjunto_residencial_control_pagos.facturas (
    id integer NOT NULL,
    id_factura uuid DEFAULT gen_random_uuid() NOT NULL,
    id_residente uuid,
    fecha_emision timestamp without time zone NOT NULL,
    fecha_vencimiento timestamp without time zone NOT NULL,
    total bigint NOT NULL,
    estado boolean NOT NULL,
    codigo character varying(50) NOT NULL
);


--ALTER TABLE conjunto_residencial_control_pagos.facturas OWNER TO postgres;

--
-- Name: facturas_id_seq; Type: SEQUENCE; Schema: conjunto_residencial_control_pagos; Owner: postgres
--

ALTER TABLE conjunto_residencial_control_pagos.facturas ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME conjunto_residencial_control_pagos.facturas_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: metodos_pagos; Type: TABLE; Schema: conjunto_residencial_control_pagos; Owner: postgres
--

CREATE TABLE conjunto_residencial_control_pagos.metodos_pagos (
    id integer NOT NULL,
    id_metodo_pago uuid DEFAULT gen_random_uuid() NOT NULL,
    codigo character varying(10) NOT NULL,
    nombre character varying(50) NOT NULL
);


--ALTER TABLE conjunto_residencial_control_pagos.metodos_pagos OWNER TO postgres;

--
-- Name: metodos_pagos_id_seq; Type: SEQUENCE; Schema: conjunto_residencial_control_pagos; Owner: postgres
--

ALTER TABLE conjunto_residencial_control_pagos.metodos_pagos ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME conjunto_residencial_control_pagos.metodos_pagos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: pagos; Type: TABLE; Schema: conjunto_residencial_control_pagos; Owner: postgres
--

CREATE TABLE conjunto_residencial_control_pagos.pagos (
    id integer NOT NULL,
    id_pago uuid DEFAULT gen_random_uuid() NOT NULL,
    id_factura uuid,
    id_residente uuid,
    fecha_pago timestamp without time zone NOT NULL,
    monto bigint NOT NULL,
    id_metodo_pago uuid
);


--ALTER TABLE conjunto_residencial_control_pagos.pagos OWNER TO postgres;

--
-- Name: pagos_id_seq; Type: SEQUENCE; Schema: conjunto_residencial_control_pagos; Owner: postgres
--

ALTER TABLE conjunto_residencial_control_pagos.pagos ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME conjunto_residencial_control_pagos.pagos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: residentes; Type: TABLE; Schema: conjunto_residencial_control_pagos; Owner: postgres
--

CREATE TABLE conjunto_residencial_control_pagos.residentes (
    id integer NOT NULL,
    id_residente uuid DEFAULT gen_random_uuid() NOT NULL,
    id_tipo_documento uuid,
    numero_documento character varying(20) NOT NULL,
    nombre_completo character varying(50) NOT NULL,
    numero_vivienda character varying(10) NOT NULL,
    id_tipo_vivienda uuid
);


--ALTER TABLE conjunto_residencial_control_pagos.residentes OWNER TO postgres;

--
-- Name: residentes_id_seq; Type: SEQUENCE; Schema: conjunto_residencial_control_pagos; Owner: postgres
--

ALTER TABLE conjunto_residencial_control_pagos.residentes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME conjunto_residencial_control_pagos.residentes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: servicios; Type: TABLE; Schema: conjunto_residencial_control_pagos; Owner: postgres
--

CREATE TABLE conjunto_residencial_control_pagos.servicios (
    id integer NOT NULL,
    id_servicio uuid DEFAULT gen_random_uuid() NOT NULL,
    codigo character varying(10) NOT NULL,
    nombre character varying(50) NOT NULL,
    descripcion text,
    costo bigint NOT NULL
);


--ALTER TABLE conjunto_residencial_control_pagos.servicios OWNER TO postgres;

--
-- Name: servicios_id_seq; Type: SEQUENCE; Schema: conjunto_residencial_control_pagos; Owner: postgres
--

ALTER TABLE conjunto_residencial_control_pagos.servicios ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME conjunto_residencial_control_pagos.servicios_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tipos_documentos; Type: TABLE; Schema: conjunto_residencial_control_pagos; Owner: postgres
--

CREATE TABLE conjunto_residencial_control_pagos.tipos_documentos (
    id integer NOT NULL,
    id_tipo_documento uuid DEFAULT gen_random_uuid() NOT NULL,
    codigo character varying(10) NOT NULL,
    nombre character varying(50) NOT NULL
);


--ALTER TABLE conjunto_residencial_control_pagos.tipos_documentos OWNER TO postgres;

--
-- Name: tipos_documentos_id_seq; Type: SEQUENCE; Schema: conjunto_residencial_control_pagos; Owner: postgres
--

ALTER TABLE conjunto_residencial_control_pagos.tipos_documentos ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME conjunto_residencial_control_pagos.tipos_documentos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tipos_viviendas; Type: TABLE; Schema: conjunto_residencial_control_pagos; Owner: postgres
--

CREATE TABLE conjunto_residencial_control_pagos.tipos_viviendas (
    id integer NOT NULL,
    id_tipo_vivienda uuid DEFAULT gen_random_uuid() NOT NULL,
    codigo character varying(10) NOT NULL,
    nombre character varying(50) NOT NULL
);


--ALTER TABLE conjunto_residencial_control_pagos.tipos_viviendas OWNER TO postgres;

--
-- Name: tipos_viviendas_id_seq; Type: SEQUENCE; Schema: conjunto_residencial_control_pagos; Owner: postgres
--

ALTER TABLE conjunto_residencial_control_pagos.tipos_viviendas ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME conjunto_residencial_control_pagos.tipos_viviendas_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: usuarios; Type: TABLE; Schema: conjunto_residencial_control_pagos; Owner: postgres
--

CREATE TABLE conjunto_residencial_control_pagos.usuarios (
    id integer NOT NULL,
    id_usuario uuid DEFAULT gen_random_uuid() NOT NULL,
    usuario character varying(255) NOT NULL,
    contrasena character varying(255) NOT NULL
);


--ALTER TABLE conjunto_residencial_control_pagos.usuarios OWNER TO postgres;

--
-- Name: usuarios_id_seq; Type: SEQUENCE; Schema: conjunto_residencial_control_pagos; Owner: postgres
--

CREATE SEQUENCE conjunto_residencial_control_pagos.usuarios_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--ALTER SEQUENCE conjunto_residencial_control_pagos.usuarios_id_seq OWNER TO postgres;

--
-- Name: usuarios_id_seq; Type: SEQUENCE OWNED BY; Schema: conjunto_residencial_control_pagos; Owner: postgres
--

ALTER SEQUENCE conjunto_residencial_control_pagos.usuarios_id_seq OWNED BY conjunto_residencial_control_pagos.usuarios.id;


--
-- Name: usuarios id; Type: DEFAULT; Schema: conjunto_residencial_control_pagos; Owner: postgres
--

ALTER TABLE ONLY conjunto_residencial_control_pagos.usuarios ALTER COLUMN id SET DEFAULT nextval('conjunto_residencial_control_pagos.usuarios_id_seq'::regclass);


--
-- Name: detalles_facturas detalles_facturas_id_key; Type: CONSTRAINT; Schema: conjunto_residencial_control_pagos; Owner: postgres
--

ALTER TABLE ONLY conjunto_residencial_control_pagos.detalles_facturas
    ADD CONSTRAINT detalles_facturas_id_key UNIQUE (id);


--
-- Name: detalles_facturas detalles_facturas_pkey; Type: CONSTRAINT; Schema: conjunto_residencial_control_pagos; Owner: postgres
--

ALTER TABLE ONLY conjunto_residencial_control_pagos.detalles_facturas
    ADD CONSTRAINT detalles_facturas_pkey PRIMARY KEY (id_detalle_factura);


--
-- Name: facturas facturas_id_key; Type: CONSTRAINT; Schema: conjunto_residencial_control_pagos; Owner: postgres
--

ALTER TABLE ONLY conjunto_residencial_control_pagos.facturas
    ADD CONSTRAINT facturas_id_key UNIQUE (id);


--
-- Name: facturas facturas_pkey; Type: CONSTRAINT; Schema: conjunto_residencial_control_pagos; Owner: postgres
--

ALTER TABLE ONLY conjunto_residencial_control_pagos.facturas
    ADD CONSTRAINT facturas_pkey PRIMARY KEY (id_factura);


--
-- Name: metodos_pagos metodos_pagos_codigo_key; Type: CONSTRAINT; Schema: conjunto_residencial_control_pagos; Owner: postgres
--

ALTER TABLE ONLY conjunto_residencial_control_pagos.metodos_pagos
    ADD CONSTRAINT metodos_pagos_codigo_key UNIQUE (codigo);


--
-- Name: metodos_pagos metodos_pagos_id_key; Type: CONSTRAINT; Schema: conjunto_residencial_control_pagos; Owner: postgres
--

ALTER TABLE ONLY conjunto_residencial_control_pagos.metodos_pagos
    ADD CONSTRAINT metodos_pagos_id_key UNIQUE (id);


--
-- Name: metodos_pagos metodos_pagos_pkey; Type: CONSTRAINT; Schema: conjunto_residencial_control_pagos; Owner: postgres
--

ALTER TABLE ONLY conjunto_residencial_control_pagos.metodos_pagos
    ADD CONSTRAINT metodos_pagos_pkey PRIMARY KEY (id_metodo_pago);


--
-- Name: pagos pagos_id_key; Type: CONSTRAINT; Schema: conjunto_residencial_control_pagos; Owner: postgres
--

ALTER TABLE ONLY conjunto_residencial_control_pagos.pagos
    ADD CONSTRAINT pagos_id_key UNIQUE (id);


--
-- Name: pagos pagos_pkey; Type: CONSTRAINT; Schema: conjunto_residencial_control_pagos; Owner: postgres
--

ALTER TABLE ONLY conjunto_residencial_control_pagos.pagos
    ADD CONSTRAINT pagos_pkey PRIMARY KEY (id_pago);


--
-- Name: residentes residentes_id_key; Type: CONSTRAINT; Schema: conjunto_residencial_control_pagos; Owner: postgres
--

ALTER TABLE ONLY conjunto_residencial_control_pagos.residentes
    ADD CONSTRAINT residentes_id_key UNIQUE (id);


--
-- Name: residentes residentes_numero_documento_key; Type: CONSTRAINT; Schema: conjunto_residencial_control_pagos; Owner: postgres
--

ALTER TABLE ONLY conjunto_residencial_control_pagos.residentes
    ADD CONSTRAINT residentes_numero_documento_key UNIQUE (numero_documento);


--
-- Name: residentes residentes_pkey; Type: CONSTRAINT; Schema: conjunto_residencial_control_pagos; Owner: postgres
--

ALTER TABLE ONLY conjunto_residencial_control_pagos.residentes
    ADD CONSTRAINT residentes_pkey PRIMARY KEY (id_residente);


--
-- Name: servicios servicios_codigo_key; Type: CONSTRAINT; Schema: conjunto_residencial_control_pagos; Owner: postgres
--

ALTER TABLE ONLY conjunto_residencial_control_pagos.servicios
    ADD CONSTRAINT servicios_codigo_key UNIQUE (codigo);


--
-- Name: servicios servicios_id_key; Type: CONSTRAINT; Schema: conjunto_residencial_control_pagos; Owner: postgres
--

ALTER TABLE ONLY conjunto_residencial_control_pagos.servicios
    ADD CONSTRAINT servicios_id_key UNIQUE (id);


--
-- Name: servicios servicios_pkey; Type: CONSTRAINT; Schema: conjunto_residencial_control_pagos; Owner: postgres
--

ALTER TABLE ONLY conjunto_residencial_control_pagos.servicios
    ADD CONSTRAINT servicios_pkey PRIMARY KEY (id_servicio);


--
-- Name: tipos_documentos tipos_documentos_codigo_key; Type: CONSTRAINT; Schema: conjunto_residencial_control_pagos; Owner: postgres
--

ALTER TABLE ONLY conjunto_residencial_control_pagos.tipos_documentos
    ADD CONSTRAINT tipos_documentos_codigo_key UNIQUE (codigo);


--
-- Name: tipos_documentos tipos_documentos_id_key; Type: CONSTRAINT; Schema: conjunto_residencial_control_pagos; Owner: postgres
--

ALTER TABLE ONLY conjunto_residencial_control_pagos.tipos_documentos
    ADD CONSTRAINT tipos_documentos_id_key UNIQUE (id);


--
-- Name: tipos_documentos tipos_documentos_pkey; Type: CONSTRAINT; Schema: conjunto_residencial_control_pagos; Owner: postgres
--

ALTER TABLE ONLY conjunto_residencial_control_pagos.tipos_documentos
    ADD CONSTRAINT tipos_documentos_pkey PRIMARY KEY (id_tipo_documento);


--
-- Name: tipos_viviendas tipos_viviendas_codigo_key; Type: CONSTRAINT; Schema: conjunto_residencial_control_pagos; Owner: postgres
--

ALTER TABLE ONLY conjunto_residencial_control_pagos.tipos_viviendas
    ADD CONSTRAINT tipos_viviendas_codigo_key UNIQUE (codigo);


--
-- Name: tipos_viviendas tipos_viviendas_id_key; Type: CONSTRAINT; Schema: conjunto_residencial_control_pagos; Owner: postgres
--

ALTER TABLE ONLY conjunto_residencial_control_pagos.tipos_viviendas
    ADD CONSTRAINT tipos_viviendas_id_key UNIQUE (id);


--
-- Name: tipos_viviendas tipos_viviendas_pkey; Type: CONSTRAINT; Schema: conjunto_residencial_control_pagos; Owner: postgres
--

ALTER TABLE ONLY conjunto_residencial_control_pagos.tipos_viviendas
    ADD CONSTRAINT tipos_viviendas_pkey PRIMARY KEY (id_tipo_vivienda);


--
-- Name: usuarios usuarios_pkey; Type: CONSTRAINT; Schema: conjunto_residencial_control_pagos; Owner: postgres
--

ALTER TABLE ONLY conjunto_residencial_control_pagos.usuarios
    ADD CONSTRAINT usuarios_pkey PRIMARY KEY (id);


--
-- Name: usuarios usuarios_usuario_key; Type: CONSTRAINT; Schema: conjunto_residencial_control_pagos; Owner: postgres
--

ALTER TABLE ONLY conjunto_residencial_control_pagos.usuarios
    ADD CONSTRAINT usuarios_usuario_key UNIQUE (usuario);


--
-- Name: detalles_facturas fk_detalle_factura_factura; Type: FK CONSTRAINT; Schema: conjunto_residencial_control_pagos; Owner: postgres
--

ALTER TABLE ONLY conjunto_residencial_control_pagos.detalles_facturas
    ADD CONSTRAINT fk_detalle_factura_factura FOREIGN KEY (id_factura) REFERENCES conjunto_residencial_control_pagos.facturas(id_factura);


--
-- Name: detalles_facturas fk_detalle_factura_servicio; Type: FK CONSTRAINT; Schema: conjunto_residencial_control_pagos; Owner: postgres
--

ALTER TABLE ONLY conjunto_residencial_control_pagos.detalles_facturas
    ADD CONSTRAINT fk_detalle_factura_servicio FOREIGN KEY (id_servicio) REFERENCES conjunto_residencial_control_pagos.servicios(id_servicio);


--
-- Name: facturas fk_factura_residente; Type: FK CONSTRAINT; Schema: conjunto_residencial_control_pagos; Owner: postgres
--

ALTER TABLE ONLY conjunto_residencial_control_pagos.facturas
    ADD CONSTRAINT fk_factura_residente FOREIGN KEY (id_residente) REFERENCES conjunto_residencial_control_pagos.residentes(id_residente);


--
-- Name: pagos fk_pago_factura; Type: FK CONSTRAINT; Schema: conjunto_residencial_control_pagos; Owner: postgres
--

ALTER TABLE ONLY conjunto_residencial_control_pagos.pagos
    ADD CONSTRAINT fk_pago_factura FOREIGN KEY (id_factura) REFERENCES conjunto_residencial_control_pagos.facturas(id_factura);


--
-- Name: pagos fk_pago_metodo_pago; Type: FK CONSTRAINT; Schema: conjunto_residencial_control_pagos; Owner: postgres
--

ALTER TABLE ONLY conjunto_residencial_control_pagos.pagos
    ADD CONSTRAINT fk_pago_metodo_pago FOREIGN KEY (id_metodo_pago) REFERENCES conjunto_residencial_control_pagos.metodos_pagos(id_metodo_pago);


--
-- Name: pagos fk_pago_residente; Type: FK CONSTRAINT; Schema: conjunto_residencial_control_pagos; Owner: postgres
--

ALTER TABLE ONLY conjunto_residencial_control_pagos.pagos
    ADD CONSTRAINT fk_pago_residente FOREIGN KEY (id_residente) REFERENCES conjunto_residencial_control_pagos.residentes(id_residente);


--
-- Name: residentes fk_residente_tipo_documento; Type: FK CONSTRAINT; Schema: conjunto_residencial_control_pagos; Owner: postgres
--

ALTER TABLE ONLY conjunto_residencial_control_pagos.residentes
    ADD CONSTRAINT fk_residente_tipo_documento FOREIGN KEY (id_tipo_documento) REFERENCES conjunto_residencial_control_pagos.tipos_documentos(id_tipo_documento);


--
-- Name: residentes fk_residente_tipo_vivienda; Type: FK CONSTRAINT; Schema: conjunto_residencial_control_pagos; Owner: postgres
--

ALTER TABLE ONLY conjunto_residencial_control_pagos.residentes
    ADD CONSTRAINT fk_residente_tipo_vivienda FOREIGN KEY (id_tipo_vivienda) REFERENCES conjunto_residencial_control_pagos.tipos_viviendas(id_tipo_vivienda);


--
-- PostgreSQL database dump complete
--

--\unrestrict ME0mcb6t6weQdUYH0vjAboX2M7EYbA18EOGoQgcAPtym7Im9GlOo4ov0OXkxisF

